version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: screenplay
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db