# Generated by Django 2.0.6 on 2018-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('poster_url', models.URLField()),
                ('script_url', models.URLField()),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rotten_tomato_rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
